### ISSUE TITLE
Incorrect segments

### ISSUE THREAD

**Issue by XachaB** [lexibank/bremerberta#6]
I find occurences of "<?>" in the segments, which seem to originate from either a dash "-" or an apostrophy, as in:

https://github.com/lexibank/bremerberta/blame/master/cldf/forms.csv#L30
https://github.com/lexibank/bremerberta/blame/master/cldf/forms.csv#L34

Moreover, there are more incorrect segments, see the TRANSCRIPTION file:

Segment | Occurrence | BIPA | CLTS SoundClass
-- | -- | -- | --
iʲ | 11 | ? | ?
eʲ | 6 | ? | ?
sh | 6 | ? | ?
iːʲ | 5 | ? | ?
lh | 5 | ? | ?
gw | 4 | ? | ?
rʃ | 4 | ? | ?
rw | 3 | ? | ?
uʷ | 3 | ? | ?
íʲ | 3 | ? | ?
óːʃ | 3 | ? | ?
<<͡>> | 2 | ? | ?
aːʷ | 2 | ? | ?
oʷ | 2 | ? | ?
rs | 2 | ? | ?
éːʃ | 2 | ? | ?
óʃ | 2 | ? | ?
óːh | 2 | ? | ?
<<ɳ>> | 1 | ? | ?
<<ʷ>> | 1 | ? | ?
aʲ | 1 | ? | ?
aːd | 1 | ? | ?
aːʲ | 1 | ? | ?
ba | 1 | ? | ?
iʷ | 1 | ? | ?
ldʒ | 1 | ? | ?
lw | 1 | ? | ?
ra | 1 | ? | ?
sʃ | 1 | ? | ?
uːʷ | 1 | ? | ?
és | 1 | ? | ?
éʃ | 1 | ? | ?
éːs | 1 | ? | ?
óːs | 1 | ? | ?
ŋ́̊ | 1 | ? | ?
ʊʷ | 1 | ? | ?
ʊ́ʷ | 1 | ? | ?
ʔw | 1 | ? | ?
̄n | 1 | ? | ?

Some of these end up as noise in the sound correspondence study.

**Comment by chrzyki** [comment]
Sorry, this profile should have been in a WIP branch, as it was just automatically generated and never edited/checked by hand.

**Comment by chrzyki** [comment]
Profile is now here: https://github.com/lexibank/bremerberta/tree/profile

Apologies, should have been there in the first place.

**Comment by XachaB** [comment]
Thanks. So, without the profile, does this mean that this dataset is not ready for integration into lexicore ?

**Comment by chrzyki** [comment]
Correct. Profile should be easy for this, though. I can have a look at this next week.
